version: 2
updates:
- package-ecosystem: "npm"
  directory: "/"
  schedule:
    interval: "weekly"
  allow:
    - dependency-type: "direct"

- package-ecosystem: "npm"
  directory: "/packages/custom-g-map"
  schedule:
    interval: "weekly"
  allow:
    - dependency-type: "direct"

- package-ecosystem: "npm"
  directory: "/packages/supplier-chain-tracking"
  schedule:
    interval: "weekly"
  allow:
    - dependency-type: "direct"
